### ISSUE TITLE
追記

### ISSUE THREAD

**Issue by ohid2819** [commerble/docs#2]
シークレットセールはできますか？（特定のユーザしか見れないページ）
商品のグルーピングはできますか（SKU単位ではなく同一商品のサマリー）

**Comment by ohid2819** [comment]
タイムセールは実現可能か
商品登録の方法で、一括登録はあるか
商品画像の制約はあるか
ブログコンテンツなどの時限表示は可能か
Google Analyticsでのイベントトラッキング、GTMの使用は可能か
広告連携可能か（Googler Merchant、Criteo、YDNなど）
ゲスト購入、会員購入それぞれ可能か
管理サイトの同時利用可能数
既存の自社EC管理に接続可能か。連携できない項目はあるか（商品、会員、受注、キャンペ）
サイト改善（CMS）は内製可能か

**Comment by ohid2819** [comment]
他のパッケージからのリプレイスは可能か、実績はあるか（ECキューブ、ECオレンジなど）
カート機能のみを利用可能か
ブログなどに直接購入ボタンを配置可能か
カートステップは省略可能か（ダイレクトカートイン）

**Comment by nabehiro** [comment]
会員移行でパスワードは移行できますか？（できません）

**Comment by nabehiro** [comment]
越境販売はできますか？
多言語対応はできますか？

**Comment by shajarax** [comment]
・外税から内税への変更は簡単にできますか？
・特定の商品カテゴリにだけ適用可能なクーポンは作れますか？
・クーポンは複数同時に使用できますか？
・商品画像のキャッシュ期間は決まっていますか？
・Wordpressのブログ記事を移行する方法はありますか？
・Googleショッピング用のフィードを作成できますか？
・対応実績のある決済方法
・デジタルコンテンツの販売は可能ですか？
・カートインした商品が保持される期間はどれくらいですか？
・レコメンド機能はありますか？

**Comment by ohid2819** [comment]
・BI連携は可能ですか？
・Webhookはありますか？
・管理サイトのIP制限は可能ですか？
・検証用環境はありますか？
・レポート機能はありますか？
・領収書出力機能(紙媒体)はありますか？
・ソーシャル連携機能（ブログ更新通知とか）はできますか？

**Comment by ohid2819** [comment]
・各データのインポート、エクスポートの可否とファイル形式について

**Comment by nabehiro** [comment]
お題ありがとうございます！転記しましたのでクローズします。
https://www.commerble.com/docs/commerble/
