### ISSUE TITLE
追加

### ISSUE THREAD

**Issue by ohid2819** [commerble/docs#3]
### 会員
* カスタム会員が必要なケースとはどのようなケースですか
* デフォルトの会員情報はどのような情報を持てますか
* 住所はいくつまで保持できますか（住所リスト）
* クレジットカードは保持できますか
* ブラックリスト機能はありますか
* 残ポイント通知機能はありますか
### 受注
* 同一ユーザ間での受注の合算はできますか
* 受注ステータスのカスタマイズは可能ですか
* 受注情報はどのような内容を持てますか
* 定期購入昨日は実現可能ですか
### カート
* 購入制限は可能ですか（おひとり様１個まで）
* ラッピング指定はできますか
### 出荷
* ピッキングリストは出力可能ですか
* 出荷時に自動メール送信は可能でしょうか（出荷通知）

**Comment by nabehiro** [comment]
ありがとうございます。
あげてもらった内容は、
https://github.com/commerble/docs/blob/master/list.md
に反映しました。
