### ISSUE TITLE
導入 文書作成

### ISSUE THREAD

**Issue by nabehiro** [commerble/docs#31]
- [ ] 導入の流れ	
	- [ ] どのようにプロジェクトを進めるか
  - [ ] カート機能のみを利用可能か？	
- [ ] 移行
  - [ ] 他のパッケージからのリプレイスは可能か、実績はあるか（ECキューブ、ECオレンジなど）
  - [ ] 会員移行でパスワードは移行できますか？（できません）
  - [ ] Wordpressのブログ記事を移行する方法はありますか？

**Comment by k1hash** [comment]
↑に書いてあることは、分散して別のページに記載されているかと思います。

**Comment by nabehiro** [comment]
@k1hash 
上のチェックリストに書いてある事への回答が網羅されていれば複数ページにわかれていてもOKです。

https://www.commerble.com/docs/commerble/introduction/
以下コンテンツをを見る限り、網羅されていますので close しますね。
